#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y

# the load balancer's configuration
DOMAIN_NAME='ollierant.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG=\
"
#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
	balance roundrobin
	server 64578-web-01 35.153.98.225:80 check
	server 64578-web-02 54.86.230.58:80 check
frontend $DOMAIN_NAME-frontend
	bind *:80
	mode http
	default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"

[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < $CONFIG_FILE)

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
	sudo sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
	echo 'ENABLED=1' >> $INIT_FILE
fi

if [ "$CONFIG_WORDS" -eq 0 ]; then
	echo -e "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
else
	start_tkn="#--$DOMAIN_NAME-params-begin--"
	end_tkn="#--$DOMAIN_NAME-params-end--"
	a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	a=$((a - 1))
	b=$((b + 1))
	sed -i "$a,$b"d "$CONFIG_FILE"
	echo -en "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
