#!/usr/bin/env bash
# runs nginx as nginx
pkill apache2
service nginx stop
sed -i 's/^user .*;$/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen .*;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx start
